from tkinter import *
from tkinter import messagebox as tmsg
import sqlite3
mydb = sqlite3.connect('ms')
cursor = mydb.cursor()
cursor.execute("CREATE TABLE IF NOT EXISTS passenger (name varchar(20), gender varchar(10), mobile int, seat int(2), journeydate date);")
root = Tk()
root.title("mybookings")
root.geometry("733x644")
root.maxsize(733, 644)
cursor.execute("CREATE TABLE IF NOT EXISTS passenger ( name varchar(20),gender varchar(10),mobile int,seat int(2),journeydate date);")
cursor.execute("CREATE TABLE IF NOT EXISTS buslist(FromPlace varchar(20), ToPlace varchar(20))")
cursor.execute("INSERT INTO buslist VALUES (?, ?)", ('guna', 'kanpur'))
name = StringVar()
seat = StringVar()
mob = IntVar()
mob_to_check = IntVar()
journey = StringVar()
def printval():
    frame = Frame(root)
    frame2 = Frame(root)
    frame3 = Frame(root)
    frame4 = Frame(root)
    frame.grid(row=0, column=0, columnspan=3)
    frame2.grid(row=1, column=0, columnspan=3)
    frame3.grid(row=2, column=0, columnspan=3)
    frame4.grid(row=3, column=0, columnspan=3)
    img = PhotoImage(file="starbus.png")
    Label(frame, text=" " * 45).grid(row=0, column=0)
    Label(frame, image=img).grid(row=0, column=1, columnspan=3)
    Label(frame2, text=" " * 55).grid(row=0, column=0)
    Label(frame2, text="ONLINE BUS BOOKING SYSTEM ", font="areal 15 bold ", bg="lightblue", fg="red", pady=5).grid(row=1, column=1, columnspan=3)
    Label(frame2, text=" " * 45).grid(row=0, column=0)
    Label(frame2, text="Enter Journey Details ", font="areal 15 bold ", bg="lightgreen", fg="darkgreen",pady=5).grid(row=2, column=1, columnspan=3)
    Label(frame3, text=" " * 30).grid(row=0, column=0)
    Label(frame3, text="To").grid(row=0, column=1)
    to = StringVar()
    toentry = Entry(frame3, textvariable=to)
    toentry.grid(row=0, column=2)
    Label(frame3, text="from").grid(row=0, column=3)
    from1 = StringVar()
    from1entry = Entry(frame3, textvariable=from1)
    from1entry.grid(row=0, column=4)
    Label(frame3, text="Journey date").grid(row=0, column=5)
    journeyentry = Entry(frame3, textvariable=journey)
    journeyentry.grid(row=0, column=6)
    def show():
        print(to.get())
        print(from1.get())
        print(journey.get())
        start = to.get()
        end = from1.get()
        cursor.execute("SELECT * FROM buslist WHERE FromPlace = ? AND ToPlace = ?", (start, end))
        result_table = cursor.fetchall()
        row_index = 1
        for row in result_table:
            def filldetails():
                global name, seat, mob, journey
                Label(frame4, text=" name").grid(row=row_index + 1, column=0)
                name=Entry(frame4)
                name.grid(row=row_index+1,column=1)
                Label(frame4, text="No. of seats ", font="areal 8 bold ").grid(row=row_index + 1, column=2)
                seatentry = Entry(frame4, textvariable=seat)
                seatentry.grid(row=row_index + 1, column=3)
                Label(frame4, text="mobile", font="areal 8 bold ").grid(row=row_index + 2, column=0)
                mobentry = Entry(frame4, textvariable=mob)
                mobentry.grid(row=row_index + 2, column=1)
                Label(frame4, text="age", font="areal 8 bold ").grid(row=row_index + 2, column=2)
                age = IntVar()
                ageentry = Entry(frame4, textvariable=age)
                ageentry.grid(row=row_index + 2, column=3)
                def giveticket():
                    global name, seat, mob, journey
                    # Creating frames
                    frame = Frame(root)
                    frame2 = Frame(root)
                    frame3 = Frame(root, relief="sunken", border=3)
                    frame4 = Frame(root)
                    frame.grid(row=0, column=0, columnspan=3)
                    frame2.grid(row=1, column=0, columnspan=3)
                    Label(root, text=" ").grid(row=2, column=0)
                    frame3.grid(row=2, column=1, columnspan=2)
                    frame4.grid(row=3, column=0, columnspan=3)
                    img = PhotoImage(file="starbus.png")
                    Label(frame, text=" " * 45).grid(row=0, column=0)
                    Label(frame, image=img).grid(row=0, column=1, columnspan=3)
                    Label(frame2, text=" " * 55).grid(row=0, column=0)
                    Label(frame2, text="ONLINE BUS BOOKING SYSTEM ", font="areal 15 bold ", bg="lightblue", fg="red", pady=5).grid(row=1, column=1, columnspan=3 )
                    Label(frame2, text=" " * 45).grid(row=0, column=0)
                    Label(frame2, text="Bus Ticket ", font="areal 15 bold ", bg="lightgreen", fg="darkgreen",pady=5).grid(row=2, column=1, columnspan=3)
                    Label(frame3, text="Passenger: ", font="areal 8 bold").grid(row=0, column=1)
                    Label(frame3, text=name.get(), font="areal 8 bold").grid(row=0, column=2)
                    Label(frame3, text="Gender: ", font="areal 8 bold").grid(row=0, column=3)
                    Label(frame3, text="No of seats: ", font="areal 8 bold").grid(row=1, column=1)
                    Label(frame3, text=seat.get(), font="areal 8 bold").grid(row=1, column=2)
                    Label(frame3, text="Travel On: ", font="areal 8 bold").grid(row=1, column=3)
                    Label(frame3, text=journey.get(), font="areal 8 bold").grid(row=1, column=4)
                    Label(frame3, text="Mobile: ", font="areal 8 bold").grid(row=2, column=1)
                    Label(frame3, text=mob.get(), font="areal 8 bold").grid(row=2, column=2)
                    insert_query = f"INSERT INTO passenger (name, gender, mobile, seat, journeydate) VALUES ('{name.get()}', 'male', {mob.get()}, {seat.get()}, '{journey.get()}');"
                    try:
                        cursor.execute(insert_query)
                        tmsg.showinfo(title="confirmation msg ", message="your seat has been booked ")
                    except Exception as e:
                        tmsg.showerror(title="Error", message=f"Error inserting data: {str(e)}")
                Button(frame4, text="book seat ", command=giveticket).grid(row=row_index + 2, column=4)
            proceed = lambda r=row: Button(frame4, text="Proceed to Book", command=filldetails).grid(row=row_index,column=2,columnspan=10)
            Button(frame4, text=f"bus", command=proceed).grid(row=row_index, column=0)
            Label(frame4, text=f"{row[0]} goes to {row[1]}").grid(row=row_index, column=1, columnspan=10)
            row_index += 1
    Button(frame3, text="submit", command=show).grid(row=0, column=7)
frame = Frame(root)
frame2 = Frame(root)
frame3 = Frame(root)
frame4 = Frame(root)
frame.grid(row=0, column=0, columnspan=3)
frame2.grid(row=1, column=0, columnspan=3)
frame3.grid(row=2, column=0, columnspan=3)
frame4.grid(row=3, column=0, columnspan=3)
img = PhotoImage(file="starbus.png")
Label(frame, text=" " * 45).grid(row=0, column=0)
Label(frame, image=img).grid(row=0, column=1)
Label(frame2, text=" " * 55).grid(row=0, column=0)
Label(frame2, text="ONLINE BUS BOOKING SYSTEM ", font="areal 15 bold ", bg="lightblue", fg="red",
      pady=5).grid(row=0, column=1, columnspan=3)
Label(frame3, text=" " * 55).grid(row=0, column=0)
Button(frame3, text="Seat Booking ", command=printval, padx=10, pady=5).grid(row=0, column=1)
def checkdata():
    global name, seat, mob, journey
    frame = Frame(root)
    frame2 = Frame(root)
    frame3 = Frame(root,relief=SUNKEN,border=6)
    frame4 = Frame(root)
    frame.grid(row=0, column=0, columnspan=3)
    frame2.grid(row=1, column=0, columnspan=3)
    frame3.grid(row=2, column=1, columnspan=3)
    frame4.grid(row=3, column=0, columnspan=3)
    img = PhotoImage(file="starbus.png")
    Label(frame, text=" " * 45).grid(row=0, column=0)
    Label(frame, image=img).grid(row=0, column=1)
    Label(frame2, text=" " * 55).grid(row=0, column=0)
    Label(frame2, text="ONLINE BUS BOOKING SYSTEM ", font="areal 15 bold ", bg="lightblue", fg="red",pady=5).grid(row=0, column=1, columnspan=3)
    Label(frame2, text="Check Your Booking ", font="areal 15 bold ", bg="lightgreen", fg="blue",pady=5).grid(row=1, column=1, columnspan=3)
    Label(frame2, text="enter your mob no.",pady=5).grid(row=2, column=0, columnspan=3)
    mob_to_checkentery = Entry(frame2,textvariable=mob_to_check)
    mob_to_checkentery.grid(row=2,column=2)
    def showdata():
        global mob_to_check
        cursor.execute("SELECT * FROM passenger WHERE mobile = ?", (mob_to_check.get(),))
        result = cursor.fetchall()
        for row in result:
            pname = row[0]
            pgender = row[1]
            pmob = row[2]
            pseat = row[3]
            pdate = row[4]
            Label(frame3,text=f"Passenger : {pname}",font="area 8 bold").grid(row=0,column=0,columnspan=2)
            Label(frame3,text=f"Mobile : {pmob}",font="area 8 bold").grid(row=0,column=2,columnspan=2)
            Label(frame3,text=f"gender : {pgender}",font="area 8 bold").grid(row=1,column=0,columnspan=2)
            Label(frame3,text=f"seats : {pseat}",font="area 8 bold").grid(row=1,column=2,columnspan=2)
            Label(frame3,text=f"Date of journey : {pdate}",font="area 8 bold").grid(row=2,column=0,columnspan=2)
    Button(frame2,text="check",command=showdata).grid(row=2,column=3)
Label(frame3, text=" " * 5).grid(row=0, column=2)
Button(frame3, text="Check Booked Seat ",command=checkdata , padx=10, pady=5).grid(row=0, column=3)
Label(frame3, text=" " * 5).grid(row=0, column=4)
Button(frame3, text="Add Bus Details ", padx=10, pady=5).grid(row=0, column=5)
Label(frame4, text=" " * 150).grid(row=0, column=0)
Label(frame4, text="for admins only ", fg="red", font="areal 7 bold ", pady=10).grid(row=0, column=1)
root.mainloop()